name: menucom_catalog
description: "Catalogo para clientes CSM"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.4

environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  pu_material:
    path: pu_material

  cupertino_icons: ^1.0.6
  get: 4.6.6
  http: ^1.2.1
  flutter_localization: ^0.2.0
  flutter_svg: ^2.0.10+1
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # rules and activating additional ones.
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
    - pubspec.yaml
    - pu_material/assets/

  fonts:
    - family: Sansation-bold
      fonts:
        - asset: fonts/Sansation_Bold.ttf
          weight: 700
        - asset: fonts/Sansation_Light.ttf
          weight: 300
        - asset: fonts/Sansation_Regular.ttf
          style: normal